import { FitnessData } from "./types";

export const seedData: FitnessData = {
  exercises: [
    {
      id: "ex-1",
      name: "Squat",
      description: "Movimento multiarticolare per gambe e core.",
      primaryMuscle: "Gambe",
      secondaryMuscles: "Addome",
      difficulty: "Intermedio",
      equipment: "Bilanciere",
      recommendedSets: 4,
      recommendedReps: 8,
      estimatedDurationMinutes: 8,
      notes: "Tenere il petto alto e controllare la discesa.",
    },
    {
      id: "ex-2",
      name: "Push up",
      description: "Spinta a corpo libero per parte alta.",
      primaryMuscle: "Petto",
      secondaryMuscles: "Braccia, Spalle",
      difficulty: "Base",
      equipment: "Corpo libero",
      recommendedSets: 3,
      recommendedReps: 12,
      estimatedDurationMinutes: 6,
      notes: "Mantenere una linea stabile dalla testa ai piedi.",
    },
    {
      id: "ex-3",
      name: "Plank",
      description: "Tenuta isometrica per stabilita del core.",
      primaryMuscle: "Addome",
      secondaryMuscles: "Spalle",
      difficulty: "Base",
      equipment: "Tappetino",
      recommendedSets: 3,
      recommendedReps: 1,
      estimatedDurationMinutes: 4,
      notes: "Non lasciare scendere il bacino.",
    },
  ],
  plans: [
    {
      id: "pl-1",
      name: "Forza full body",
      description: "Scheda bilanciata per aumentare forza generale.",
      goal: "Forza",
      level: "Intermedio",
      durationMinutes: 45,
      frequencyPerWeek: 3,
      exerciseIds: ["ex-1", "ex-2", "ex-3"],
      restSeconds: 90,
      days: [
        {
          id: "day-1",
          name: "Giorno 1",
          items: [
            { id: "pe-1", exerciseId: "ex-1", sets: 4, reps: 8 },
            { id: "pe-2", exerciseId: "ex-2", sets: 3, reps: 12 },
          ],
        },
        {
          id: "day-2",
          name: "Giorno 2",
          items: [
            { id: "pe-3", exerciseId: "ex-2", sets: 4, reps: 10 },
            { id: "pe-4", exerciseId: "ex-3", sets: 3, reps: 45 },
          ],
        },
      ],
      notes: "Recupero generale consigliato tra gli esercizi.",
    },
  ],
  sessions: [
    {
      id: "se-1",
      title: "Full body A",
      date: "2026-06-29",
      type: "Forza",
      planId: "pl-1",
      planDayId: "day-1",
      exerciseIds: ["ex-1", "ex-2"],
      status: "Da svolgere",
      notes: "Concentrarsi sulla tecnica.",
    },
  ],
  workouts: [
    {
      id: "wo-1",
      title: "Full body completato",
      date: "2026-06-24",
      planId: "pl-1",
      planDayId: "day-1",
      durationMinutes: 52,
      exerciseLoads: [
        { planItemId: "pe-1", loadKg: 60 },
        { planItemId: "pe-2", loadKg: 0 },
      ],
      effort: 7,
      notes: "Buona energia, aumentare poco il carico nello squat.",
    },
  ],
  goals: [
    {
      id: "go-1",
      title: "Allenarsi 12 volte",
      description: "Completare 12 allenamenti nel mese.",
      category: "Frequenza",
      target: 12,
      current: 4,
      startDate: "2026-06-01",
      dueDate: "2026-06-30",
      status: "Aperto",
      notes: "Aggiornare dopo ogni allenamento completato.",
    },
  ],
};
